import {
    HiOutlineChartSquareBar,
    HiOutlineUserGroup,
    HiOutlineTrendingUp,
    HiOutlineUserCircle,
    HiOutlineBookOpen,
    HiOutlineCurrencyDollar,
    HiOutlineShieldCheck,
    HiOutlineColorSwatch,
    HiOutlineChatAlt,
    HiOutlineDesktopComputer,
    HiOutlinePaperAirplane,
    HiOutlineChartPie,
    HiOutlineUserAdd,
    HiOutlineKey,
    HiOutlineBan,
    HiOutlineHand,
    HiOutlineDocumentText,
    HiOutlineTemplate,
    HiOutlineLockClosed,
    HiOutlineDocumentDuplicate,
    HiOutlineViewGridAdd,
    HiOutlineShare,
    HiOutlineVariable,
    HiOutlineCode,
    HiOutlineShoppingCart,
    HiOutlineTruck,
    HiOutlineViewGrid,
    HiOutlineTag,
    HiOutlineCreditCard,
    HiOutlineShoppingBag,
    HiOutlineChatAlt2,
    HiOutlineTicket,
    HiOutlineSpeakerphone,
    HiOutlineMail,
    HiOutlineChartBar,
    HiOutlineCog,
    HiOutlinePresentationChartLine,
    HiOutlineCube,
    HiOutlineFlag,
} from 'react-icons/hi'

export type NavigationIcons = Record<string, JSX.Element>

const navigationIcon: NavigationIcons = {

    dashboard: <HiOutlinePresentationChartLine />,
    homePage: <HiOutlineDesktopComputer />,
    admin: <HiOutlineShieldCheck />,
    customers: <HiOutlineUserGroup />,
    product: <HiOutlineShoppingCart />,
    condition: <HiOutlineTag />,
    binStore: <HiOutlineTemplate />,
    auctionPage: <HiOutlineCube />,
    pallet: <HiOutlineViewGrid />,
    truckLoads: <HiOutlineTruck />,
    category: <HiOutlineColorSwatch />,
    payment: <HiOutlineCreditCard />,
    shipping: <HiOutlineShoppingBag />,
    messaging: <HiOutlineChatAlt2 />,
    tickets: <HiOutlineTicket />,
    promotions: <HiOutlineSpeakerphone />,
    marketing: <HiOutlineMail />,
    reports: <HiOutlineChartBar />,
    settings: <HiOutlineCog />,
    coupon: <HiOutlineColorSwatch />,
    pro_campaign: <HiOutlineFlag />,





    apps: <HiOutlineViewGridAdd />,
    project: <HiOutlineChartSquareBar />,
    crm: <HiOutlineUserGroup />,
    sales: <HiOutlineTrendingUp />,
    crypto: <HiOutlineCurrencyDollar />,
    knowledgeBase: <HiOutlineBookOpen />,
    account: <HiOutlineUserCircle />,
    uiComponents: <HiOutlineTemplate />,
    common: <HiOutlineColorSwatch />,
    feedback: <HiOutlineChatAlt />,
    dataDisplay: <HiOutlineDesktopComputer />,
    forms: <HiOutlineDocumentText />,
    navigation: <HiOutlinePaperAirplane />,
    graph: <HiOutlineChartPie />,
    authentication: <HiOutlineLockClosed />,
    signIn: <HiOutlineShieldCheck />,
    signUp: <HiOutlineUserAdd />,
    forgotPassword: <HiOutlineLockClosed />,
    resetPassword: <HiOutlineKey />,
    pages: <HiOutlineDocumentDuplicate />,
    welcome: <HiOutlineHand />,
    accessDenied: <HiOutlineBan />,
    guide: <HiOutlineBookOpen />,
    documentation: <HiOutlineDocumentText />,
    sharedComponentDoc: <HiOutlineShare />,
    utilsDoc: <HiOutlineVariable />,
    changeLog: <HiOutlineCode />,
}

export default navigationIcon
